#端口号及访问路径
server:
  port: 9528
  servlet:
    context-path: /jtsec
#数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    analysis:
       type: com.alibaba.druid.pool.DruidDataSource
       driver-class-name: com.mysql.cj.jdbc.Driver
       initialize: true #指定初始化数据源，是否用data.sql来初始化，默认: true
       url: jdbc:mysql://47.95.0.193:3306/jtsec-mc-log-analysis?useUnicode=true&characterEncoding=utf-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
       username: root
       password: root
    jtsec:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      initialize: true #指定初始化数据源，是否用data.sql来初始化，默认: true
      url: jdbc:mysql://localhost:3306/jtsec_log?useUnicode=true&characterEncoding=utf-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
      username: root
      password: root
  redis:
    host: 47.95.0.193
    # Redis服务器连接端口
    port: 12345
    password: liyanpeng
    jedis:
      pool:
     # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
     # 连接池中的最小空闲连接
        min-idle: 0
     # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
     # 连接池中的最大空闲连接
        max-idle: 100
        max-total: 200
    # 连接超时时间（毫秒）
    timeout: 60ms
  dubbo:
    server: true
#注册在注册中心的名称，唯一标识，请勿重复
    application:
      id: provider
      name: live-dubbo-provider
#注册中心地址，zookeeper集群，启动输出可以看见链接了多个
#单zookeeper服务：zookeeper://127.0.0.1:2181
    registry:
      address: zookeeper://47.95.0.193:2181
#暴露服务方式
#暴露服务端口 （默认是20880，修改端口，不同的服务提供者端口不能重复）
    protocol:
      name: dubbo
      port: 20880
      status: server
#mybaties扫描配置
  kafka:
    #kafka服务器地址
    bootstrap-servers: 47.95.0.193:9092
    #key-value序列化
    consumer:
      group-id: jtsec-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
# 日志logback
logging:
  level:
     com.jtsec.mc.log.analysis.mapper: debug
     com.jtsec.mc.log.jtsec.mapper: debug
